name: CI

on:
  pull_request:
    paths-ignore:
      - '**.md'    
  push:    
    branches:
      - master
      # - releases/*
    paths-ignore:
      - '**.md'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 10.18.1 (for Cloud Functions Node v10)
        uses: actions/setup-node@v1
        with:
          node-version: 10.18.1
      # - uses: expo/expo-github-action@v5
      #   with:
      #     expo-version: 3.x
      #     expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
      #     expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - run: yarn install
      - run: yarn lint
      # - run: yarn test
